services:
  backend:
    build:
      context: ./backend/blog/
      dockerfile: Dockerfile
    environment:
      BLOG_GOOGLE_CLIENT_ID: ${BLOG_GOOGLE_CLIENT_ID}
      BLOG_GOOGLE_CLIENT_SECRET: ${BLOG_GOOGLE_CLIENT_SECRET}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    container_name: backend_spring
    networks:
    - blog_network

  nginx-static:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: nginx_static
    ports:
      - "80:80"
    networks:
    - blog_network

  postgres:
    image: postgres:18
    container_name: blog_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - blog_network  


networks:
  blog_network:
    name: blog_network

volumes:
  pgdata: